spring:
  config:
    activate:
      on-profile: local
    import: application-database.yml, application-swagger.yml

  data:
    redis:
      host: localhost
      port: 6379

auth:
  jwt:
    secret: ${JWT_SECRET}

server:
  port: 8080