spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_URL}?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${DATABASE_NAME}
    password: ${DATABASE_PW}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    database-platform: org.hibernate.dialect.MySQLDialect

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: otakubucket
      region:
        static: ap-northeast-2
      stack:
        auto: false
  cdn:
    url: https://dncn3ig9c12kd.cloudfront.net/

